



SAEBA:
	LD	A,TIMEFADE
	LD	(FADE_V),A
	CALL	FADE_ON


	LD	B,2
	LD	DE,TMESG
SAEB0	LD	A,(DE)
	LD	L,A
	INC	DE
	LD	A,(DE)
	INC	DE
	LD	H,A
	PUSH	DE
	PUSH	BC

	LD	A,(PAG_ACT)
	LD	B,A
	LD	D,20
	LD	E,20
	CALL	PRINTF


	LD	C,5
SAEB2	LD	B,255
SAEB1	EI
	HALT
	DJNZ	SAEB1
	DEC	C
	JR	NZ,SAEB2

	CALL	WAIT_COM
	LD	A,(PAG_ACT)
	LD	B,A
	LD	A,0DDh
	LD	HL,LIMPIA_SCR
	CALL	LIMPIA_PAN


	POP	BC
	POP	DE
	DJNZ	SAEB0

	LD	DE,FINDEMO
	LD	HL,DEMOBUFFER
	LD	A,GET_DIR_BUFF
	CALL	ADD_EXCP

	LD	A,TIMEFADE
	LD	(FADE_V),A
	CALL	FADE_OFF

	RET

TMESG:	DW	MESSG
	DW	MESSG1

MESSG:		DB "%4COMO TODO BUEN CUENTO%N"
		DB "SIEMPRE SE DEBE EMPEZAR%n"
		DB "CON EL TIPICO TOPICO;%n"
		DB "CON EL "
		DB 39
		DB "HACE MUCHO TIEMPO...%n%n"

		DB "Y, SIGUIENDO CON EL HILO...%n"
		DB 39
		DB "...EXISTIA UN PAIS DESOLADO,%n"
		DB "DONDE SOLO HABITABA EL HOMBRE,%n"
		DB "JUNTO A LOS PASTOS..., Y EL GANADO%n%n"

		DB 39
		DB "EL LIDER DE LA TRIBU, PREOCUPADO%n"
		DB "MANDO AL REUNIR A SUS MAS BRAVOS CABALLEROS%n"
		DB "CON EL PROPOSITO DE ENCONTRAR%n"
		DB "LA FUENTE CON LA QUE DAR VIDA AL POBLADO%n"
		DB 0


MESSG1:		DB 39
		DB "NINGUN PALADIN SE OFRECIO VOLUNTARIO%n"
		DB "YA QUE ESTABAN ATERRORIZADOS POR%n"
		DB "EL PODEROSO %bSAEBA%l%n"
		DB "QUIEN, ESPADA EN MANO,%n"
		DB "REDUCIA LA VOLUNTAD DE SUS HOMBRES%n"
		DB "CONVIRTIENDOLES EN ESCLAVOS%n%n"

		DB 39
		DB "EL GRAN LIDER SE ENFRENTA ANTE UN GRAN DILEMA:%n"
		DB "SALE EN BUSCA DE LA FUENTE, SALVANDO ASI A SU PUEBLO?%n"
		DB "O SE ENFRENTA A %bSAEBA%l,CON SU INFINITA HAMBRE DE MUERTE?%n"
		DB 0






DEMOBUFFER:	DB	80h
	DB	DERECHA,DERECHA,DERECHA,DERECHA,DERECHA
	DB	DERECHA,DERECHA,DERECHA,DERECHA,DERECHA
	DB	DERECHA,DERECHA,DERECHA,DERECHA,DERECHA
	DB	DERECHA,DERECHA,DERECHA,DERECHA,DERECHA
	DB	DERECHA,DERECHA,DERECHA,DERECHA,DERECHA
	DB	DERECHA,DERECHA,DERECHA

	DB	ABAJO,ABAJO,ABAJO,ABAJO,ABAJO
	DB	ABAJO,ABAJO,ABAJO,ABAJO,ABAJO
	DB	ABAJO,ABAJO,ABAJO,ABAJO,ABAJO
	DB	ABAJO,ABAJO,80h,80h

	DB	DERECHA,DERECHA,DERECHA,DERECHA,DERECHA
	DB	DERECHA,DERECHA,DERECHA,DERECHA
	DB	ARRIBA,ARRIBA,ARRIBA,ARRIBA,ARRIBA
	DB	80h,80h,0FFh



FINDEMO	CALL	UP_EXCP
	RET
